ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "orgNom" TEXT;
ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "orgLogoBase64" TEXT;
ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "masquerMM" BOOLEAN NOT NULL DEFAULT false;
