ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "organisateursTexte" TEXT;
ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "contactNom" TEXT;
ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE "Cursus" ADD COLUMN IF NOT EXISTS "contactTelephone" TEXT;
ALTER TABLE "CursusEnseignant" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'ENSEIGNANT';
ALTER TABLE "CursusEnseignant" ADD COLUMN IF NOT EXISTS "estOrganisateur" BOOLEAN NOT NULL DEFAULT false;
